// Code generated by "go-enum -type JobType -trimprefix JobType -transform kebab"; DO NOT EDIT.

package printing

import (
	"database/sql"
	"database/sql/driver"
	"encoding"
	"encoding/json"
	"fmt"
	"strconv"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[invalidJobType-0]
	_ = x[JobTypeList-1]
	_ = x[JobTypeForm-2]
}

const _JobType_name = "invalid-job-typelistform"

var _JobType_index = [...]uint8{0, 16, 20, 24}

func _() {
	var _nil_JobType_value = func() (val JobType) { return }()

	// An "cannot convert JobType literal (type JobType) to type fmt.Stringer" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ fmt.Stringer = _nil_JobType_value
}

func (i JobType) String() string {
	if i < 0 || i >= JobType(len(_JobType_index)-1) {
		return "JobType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _JobType_name[_JobType_index[i]:_JobType_index[i+1]]
}

var _JobType_values = []JobType{0, 1, 2}

var _JobType_name_to_values = map[string]JobType{
	_JobType_name[0:16]:  0,
	_JobType_name[16:20]: 1,
	_JobType_name[20:24]: 2,
}

// ParseJobTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ParseJobTypeString(s string) (JobType, error) {
	if val, ok := _JobType_name_to_values[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%[1]s does not belong to JobType values", s)
}

// JobTypeValues returns all values of the enum
func JobTypeValues() []JobType {
	return _JobType_values
}

// IsAJobType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i JobType) Registered() bool {
	for _, v := range _JobType_values {
		if i == v {
			return true
		}
	}
	return false
}

func _() {
	var _nil_JobType_value = func() (val JobType) { return }()

	// An "cannot convert JobType literal (type JobType) to type encoding.BinaryMarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.BinaryMarshaler = &_nil_JobType_value

	// An "cannot convert JobType literal (type JobType) to type encoding.BinaryUnmarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.BinaryUnmarshaler = &_nil_JobType_value
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for JobType
func (i JobType) MarshalBinary() (data []byte, err error) {
	return []byte(i.String()), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for JobType
func (i *JobType) UnmarshalBinary(data []byte) error {
	var err error
	*i, err = ParseJobTypeString(string(data))
	return err
}

func _() {
	var _nil_JobType_value = func() (val JobType) { return }()

	// An "cannot convert JobType literal (type JobType) to type json.Marshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ json.Marshaler = _nil_JobType_value

	// An "cannot convert JobType literal (type JobType) to type encoding.Unmarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ json.Unmarshaler = &_nil_JobType_value
}

// MarshalJSON implements the json.Marshaler interface for JobType
func (i JobType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for JobType
func (i *JobType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("JobType should be a string, got %[1]s", data)
	}

	var err error
	*i, err = ParseJobTypeString(s)
	return err
}

func _() {
	var _nil_JobType_value = func() (val JobType) { return }()

	// An "cannot convert JobType literal (type JobType) to type encoding.TextMarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.TextMarshaler = _nil_JobType_value

	// An "cannot convert JobType literal (type JobType) to type encoding.TextUnmarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.TextUnmarshaler = &_nil_JobType_value
}

// MarshalText implements the encoding.TextMarshaler interface for JobType
func (i JobType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for JobType
func (i *JobType) UnmarshalText(text []byte) error {
	var err error
	*i, err = ParseJobTypeString(string(text))
	return err
}

//func _() {
//	var _nil_JobType_value = func() (val JobType) { return }()
//
//	// An "cannot convert JobType literal (type JobType) to type yaml.Marshaler" compiler error signifies that the base type have changed.
//	// Re-run the go-enum command to generate them again.
//	var _ yaml.Marshaler = _nil_JobType_value
//
//	// An "cannot convert JobType literal (type JobType) to type yaml.Unmarshaler" compiler error signifies that the base type have changed.
//	// Re-run the go-enum command to generate them again.
//	var _ yaml.Unmarshaler = &_nil_JobType_value
//}

// MarshalYAML implements a YAML Marshaler for JobType
func (i JobType) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for JobType
func (i *JobType) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = ParseJobTypeString(s)
	return err
}

func _() {
	var _nil_JobType_value = func() (val JobType) { return }()

	// An "cannot convert JobType literal (type JobType) to type driver.Valuer" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ driver.Valuer = _nil_JobType_value

	// An "cannot convert JobType literal (type JobType) to type sql.Scanner" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ sql.Scanner = &_nil_JobType_value
}

func (i JobType) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *JobType) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	str, ok := value.(string)
	if !ok {
		bytes, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("value is not a byte slice")
		}

		str = string(bytes[:])
	}

	val, err := ParseJobTypeString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}

// JobTypeSliceContains reports whether sunEnums is within enums.
func JobTypeSliceContains(enums []JobType, sunEnums ...JobType) bool {
	var seenEnums = map[JobType]bool{}
	for _, e := range sunEnums {
		seenEnums[e] = false
	}

	for _, v := range enums {
		if _, has := seenEnums[v]; has {
			seenEnums[v] = true
		}
	}

	for _, seen := range seenEnums {
		if !seen {
			return false
		}
	}

	return true
}

// JobTypeSliceContainsAny reports whether any sunEnum is within enums.
func JobTypeSliceContainsAny(enums []JobType, sunEnums ...JobType) bool {
	var seenEnums = map[JobType]struct{}{}
	for _, e := range sunEnums {
		seenEnums[e] = struct{}{}
	}

	for _, v := range enums {
		if _, has := seenEnums[v]; has {
			return true
		}
	}

	return false
}
