// Code generated by "go-enum -type Orientation -trimprefix Orientation -transform kebab"; DO NOT EDIT.

package printing

import (
	"database/sql"
	"database/sql/driver"
	"encoding"
	"encoding/json"
	"fmt"
	"strconv"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[invalidOrientation-0]
	_ = x[OrientationPortrait-1]
	_ = x[OrientationLandscape-2]
}

const _Orientation_name = "invalid-orientationportraitlandscape"

var _Orientation_index = [...]uint8{0, 19, 27, 36}

func _() {
	var _nil_Orientation_value = func() (val Orientation) { return }()

	// An "cannot convert Orientation literal (type Orientation) to type fmt.Stringer" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ fmt.Stringer = _nil_Orientation_value
}

func (i Orientation) String() string {
	if i < 0 || i >= Orientation(len(_Orientation_index)-1) {
		return "Orientation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Orientation_name[_Orientation_index[i]:_Orientation_index[i+1]]
}

var _Orientation_values = []Orientation{0, 1, 2}

var _Orientation_name_to_values = map[string]Orientation{
	_Orientation_name[0:19]:  0,
	_Orientation_name[19:27]: 1,
	_Orientation_name[27:36]: 2,
}

// ParseOrientationString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ParseOrientationString(s string) (Orientation, error) {
	if val, ok := _Orientation_name_to_values[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%[1]s does not belong to Orientation values", s)
}

// OrientationValues returns all values of the enum
func OrientationValues() []Orientation {
	return _Orientation_values
}

// IsAOrientation returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Orientation) Registered() bool {
	for _, v := range _Orientation_values {
		if i == v {
			return true
		}
	}
	return false
}

func _() {
	var _nil_Orientation_value = func() (val Orientation) { return }()

	// An "cannot convert Orientation literal (type Orientation) to type encoding.BinaryMarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.BinaryMarshaler = &_nil_Orientation_value

	// An "cannot convert Orientation literal (type Orientation) to type encoding.BinaryUnmarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.BinaryUnmarshaler = &_nil_Orientation_value
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for Orientation
func (i Orientation) MarshalBinary() (data []byte, err error) {
	return []byte(i.String()), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for Orientation
func (i *Orientation) UnmarshalBinary(data []byte) error {
	var err error
	*i, err = ParseOrientationString(string(data))
	return err
}

func _() {
	var _nil_Orientation_value = func() (val Orientation) { return }()

	// An "cannot convert Orientation literal (type Orientation) to type json.Marshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ json.Marshaler = _nil_Orientation_value

	// An "cannot convert Orientation literal (type Orientation) to type encoding.Unmarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ json.Unmarshaler = &_nil_Orientation_value
}

// MarshalJSON implements the json.Marshaler interface for Orientation
func (i Orientation) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Orientation
func (i *Orientation) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Orientation should be a string, got %[1]s", data)
	}

	var err error
	*i, err = ParseOrientationString(s)
	return err
}

func _() {
	var _nil_Orientation_value = func() (val Orientation) { return }()

	// An "cannot convert Orientation literal (type Orientation) to type encoding.TextMarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.TextMarshaler = _nil_Orientation_value

	// An "cannot convert Orientation literal (type Orientation) to type encoding.TextUnmarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.TextUnmarshaler = &_nil_Orientation_value
}

// MarshalText implements the encoding.TextMarshaler interface for Orientation
func (i Orientation) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Orientation
func (i *Orientation) UnmarshalText(text []byte) error {
	var err error
	*i, err = ParseOrientationString(string(text))
	return err
}

//func _() {
//	var _nil_Orientation_value = func() (val Orientation) { return }()
//
//	// An "cannot convert Orientation literal (type Orientation) to type yaml.Marshaler" compiler error signifies that the base type have changed.
//	// Re-run the go-enum command to generate them again.
//	var _ yaml.Marshaler = _nil_Orientation_value
//
//	// An "cannot convert Orientation literal (type Orientation) to type yaml.Unmarshaler" compiler error signifies that the base type have changed.
//	// Re-run the go-enum command to generate them again.
//	var _ yaml.Unmarshaler = &_nil_Orientation_value
//}

// MarshalYAML implements a YAML Marshaler for Orientation
func (i Orientation) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for Orientation
func (i *Orientation) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = ParseOrientationString(s)
	return err
}

func _() {
	var _nil_Orientation_value = func() (val Orientation) { return }()

	// An "cannot convert Orientation literal (type Orientation) to type driver.Valuer" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ driver.Valuer = _nil_Orientation_value

	// An "cannot convert Orientation literal (type Orientation) to type sql.Scanner" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ sql.Scanner = &_nil_Orientation_value
}

func (i Orientation) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *Orientation) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	str, ok := value.(string)
	if !ok {
		bytes, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("value is not a byte slice")
		}

		str = string(bytes[:])
	}

	val, err := ParseOrientationString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}

// OrientationSliceContains reports whether sunEnums is within enums.
func OrientationSliceContains(enums []Orientation, sunEnums ...Orientation) bool {
	var seenEnums = map[Orientation]bool{}
	for _, e := range sunEnums {
		seenEnums[e] = false
	}

	for _, v := range enums {
		if _, has := seenEnums[v]; has {
			seenEnums[v] = true
		}
	}

	for _, seen := range seenEnums {
		if !seen {
			return false
		}
	}

	return true
}

// OrientationSliceContainsAny reports whether any sunEnum is within enums.
func OrientationSliceContainsAny(enums []Orientation, sunEnums ...Orientation) bool {
	var seenEnums = map[Orientation]struct{}{}
	for _, e := range sunEnums {
		seenEnums[e] = struct{}{}
	}

	for _, v := range enums {
		if _, has := seenEnums[v]; has {
			return true
		}
	}

	return false
}
